version: '3.8'
services:
  hbase:
    image: harisekhon/hbase
    container_name: hbase_inventory
    ports:
      - "8080:8080"   # HBase REST API (Stargate)
      - "16010:16010" # HBase Master Web UI
      - "2181:2181"   # ZooKeeper
      - "9090:9090"   # Thrift API
    volumes:
      - hbase_data:/hbase
    restart: always

volumes:
  hbase_data:
